# Application Name & Server Configuration
spring.application.name=CMD_Appointments
server.port=8081

# Set Jackson (Spring's JSON processor) to use dd-MM-yyyy
spring.jackson.date-format=dd-MM-yyyy
spring.jackson.serialization.write-dates-as-timestamps=false

# Old Server Configuration (commented out for reference)
#spring.datasource.url=jdbc:sqlserver://cmdapplication.database.windows.net:1433;database=CMD_Database;user=cmdadmin;password=Password@123;encrypt=true;trustServerCertificate=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#spring.datasource.url=jdbc:mysql://localhost:3306/appointments_db?createDatabaseIfNotExist=true&useSSL=true
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# MySQL Database Connection
spring.datasource.url=jdbc:mysql://cmd-dev.mysql.database.azure.com:3306/cmd?useSSL=true&requireSSL=true
spring.datasource.username=cmdadmin
spring.datasource.password=Mypassword@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# SSL Configuration (Ensure the SSL CA certificate is in place)
spring.datasource.hikari.data-source-properties.ssl-mode=require
spring.datasource.hikari.data-source-properties.ssl-ca-file=path/to/DigiCertGlobalRootCA.crt.pem

# Hikari Connection Pool Configuration
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=12
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.id.new_generator_mappings=true
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Jackson Configuration
spring.jackson.serialization.fail-on-empty-beans=false

# Spring Boot Security (Uncomment if needed)
#spring.security.user.name=admin
#spring.security.user.password=admin123
#spring.security.user.roles=ADMIN
#spring.security.user.name=user
#spring.security.user.password=user123
#spring.security.user.roles=USER

# Circular References (Spring Boot 3.x+)
spring.main.allow-circular-references=true


doctorApiUrl = "https://cmd-doctors-be-service.azurewebsites.net/api"
patientApiUrl = "https://cmd-doctors-be-service.azurewebsites.net/api"